version: "3.8"
services:
    mysql:
        image: mysql:latest
        container_name: expense-tracker-db
        environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: expense-tracker
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data:
